[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -D CORE_DEBUG_LEVEL=0
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    mathieucarbou/ESPAsyncWebServer @ ^3.3.17
    mathieucarbou/AsyncTCP @ ^3.2.14
