[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS
    -D BOARD_INFO=\"Wemos\ D1\ Mini.\ Pins:\ D1=5,\ D2=4,\ D3=0,\ D4/LED=2,\ D5=14,\ D6=12,\ D7=13,\ D8=15.\"
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D BOARD_INFO=\"ESP32\ DevKit.\ Built-in\ LED=2.\"
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    mathieucarbou/ESPAsyncWebServer @ ^3.3.17
    mathieucarbou/AsyncTCP @ ^3.2.14

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS
    -D BOARD_INFO=\"NodeMCU\ v2.\ Pins:\ D1=5,\ D2=4,\ D3=0,\ D4/LED=2,\ D5=14,\ D6=12,\ D7=13,\ D8=15.\"
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_INFO=\"ESP32-C3.\ Built-in\ LED=8.\"
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    mathieucarbou/ESPAsyncWebServer @ ^3.3.17
    mathieucarbou/AsyncTCP @ ^3.2.14

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_INFO=\"ESP32-S3.\ Built-in\ LED=2.\"
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    mathieucarbou/ESPAsyncWebServer @ ^3.3.17
    mathieucarbou/AsyncTCP @ ^3.2.14

[env:esp32-s2]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_INFO=\"ESP32-S2.\ Built-in\ LED=15.\"
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    mathieucarbou/ESPAsyncWebServer @ ^3.3.17
    mathieucarbou/AsyncTCP @ ^3.2.14
